name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # run daily
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow pushing commits

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: coderrdikshant
